apiVersion: apps/v1
kind: Deployment
metadata:
  name: infnet-guia-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: infnet-guia-app
  template:
    metadata:
      labels:
        app: infnet-guia-app
    spec:
      containers:
        - name: infnet-guia-app
          image: cleversantoro/infnet-guia-app:1.2 # não recomendado, só usando latest pra desenvolvimento
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: infnet-guia-app-service
spec:
  type: LoadBalancer
  selector:
    app: infnet-guia-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
